config/routes.rb
BuddyList::Application.routes.draw do
  resources :buddies

  get "home/index"
  devise_for :users

  root :to => "home#index"

end

app/models/buddy.rb
class Buddy < ActiveRecord::Base
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable, :lockable and :timeoutable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/buddies_controller.rb
class BuddiesController < InheritedController
end

app/controllers/buddylist_controller.rb
class BuddylistController < ApplicationController
  before_filter :authenticate_user!
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/inherited_controller.rb
class InheritedController < BuddylistController
  inherit_resources
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/buddies_helper.rb
module BuddiesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/buddies/_form.html.erb
<%= form_for(@buddy) do |f| %>
  <% if @buddy.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@buddy.errors.count, "error") %> prohibited this buddy from being saved:</h2>

      <ul>
      <% @buddy.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :address %><br />
    <%= f.text_area :address %>
  </div>
  <div class="field">
    <%= f.label :user %><br />
    <%= f.text_field :user %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/buddies/edit.html.erb
<h1>Editing buddy</h1>

<%= render 'form' %>

<%= link_to 'Show', @buddy %> |
<%= link_to 'Back', buddies_path %>

app/views/buddies/index.html.erb
<h1>Listing buddies</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Email</th>
    <th>Address</th>
    <th>User</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @buddies.each do |buddy| %>
  <tr>
    <td><%= buddy.name %></td>
    <td><%= buddy.email %></td>
    <td><%= buddy.address %></td>
    <td><%= buddy.user %></td>
    <td><%= link_to 'Show', buddy %></td>
    <td><%= link_to 'Edit', edit_buddy_path(buddy) %></td>
    <td><%= link_to 'Destroy', buddy, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Buddy', new_buddy_path %>

app/views/buddies/new.html.erb
<h1>New buddy</h1>

<%= render 'form' %>

<%= link_to 'Back', buddies_path %>

app/views/buddies/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @buddy.name %>
</p>

<p>
  <b>Email:</b>
  <%= @buddy.email %>
</p>

<p>
  <b>Address:</b>
  <%= @buddy.address %>
</p>

<p>
  <b>User:</b>
  <%= @buddy.user %>
</p>


<%= link_to 'Edit', edit_buddy_path(@buddy) %> |
<%= link_to 'Back', buddies_path %>

app/views/home/index.html.haml
%h1 Home#index
%p Find me in app/views/home/index.html.haml

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>BuddyList</title>
  <%= stylesheet_link_tag :all %>
  <%= javascript_include_tag :defaults %>
  <%= csrf_meta_tag %>
</head>
<body>
<%=alert%>
<%=notice%>
<%= yield %>

</body>
</html>